config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end

  resources :videos

  devise_for :users
  #root to: 'home#index'
  root to: 'videos#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # assoc
  has_many :videos
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/video.rb
class Video < ApplicationRecord
  validates_presence_of :video_url
  #association
  belongs_to :user
  def like!
	  self.likes += 1
	  save
  end
  def dislike!
	  self.likes -= 1
	  save
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:username, :name])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # Checks if user is signed in before running controller, functionality provided by devise
  #before_action :set_user, only: [:show]
  #before_action :set_current_user, only: [:edit, :update]
  def index
    @users = User.all
  end
  def show
    @user = User.find(params[:id])
    authorize @user
  end
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end
  def set_current_user
    @user = current_user
  end
  def user_params
    params.require(:user).permit(:email)
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  #before_action :authenticate_user!
  before_action :set_video, only: [:show, :edit, :like, :dislike]
  # All published videos
  def index
	  @videos = Video.all
  end
  def show
    @videos = Video.find(params[:id])
    Rails.logger.debug("video show #{@videos.attributes.inspect}")
  end
  def new
    Rails.logger.debug("video new")
    @video = Video.new
  end
  def edit
  end
  def create
    Rails.logger.debug("video create")
    @video = Video.new(video_params)
    if @video.video_url.blank?
      Rails.logger.debug("video url empty")
      respond_to do |format|
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    else
      @video.user_id = current_user.id
      # thumbnail root_url
      urlname = @video.video_url.gsub(/http(?:s?):\/\/(?:www\.)?youtu(?:be\.com\/watch\?v=)/,'\1')
      Rails.logger.debug("#{urlname}")
      @video.thumbnail_url = "http://img.youtube.com/vi/" + urlname + "/default.jpg"
      @video.video_url = "https://www.youtube.com/embed/" + urlname
      respond_to do |format|
        if @video.save!
          Rails.logger.debug("video save")
          format.html { redirect_to @video, notice: 'Video was successfully created.' }
          format.json { render :show, status: :created, location: @video }
        else
          Rails.logger.debug("video error")
          format.html { render :new }
          format.json { render json: @video.errors, status: :unprocessable_entity }
        end
      end
    end
  end
  # Likes video, increment likes count
  def like
    @video.like!
  end
  # Dislikes video, increment likes count
  def dislike
    @video.dislike!
  end
  private
  def set_video
    Rails.logger.debug(params[:id])
    if params[:id].to_i.to_s == params[:id]
      @video = Video.find(params[:id])
    else
      params[:id] = "1"
      Rails.logger.debug("video nil")
    end
  end
  def video_params
    params.require(:video).permit(:video_url, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/content_helper.rb
module ContentHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/home/index.html.erb
<h1 class="semibold text-2xl">Welcome to Kickoff!</h1>
<p class="lead">Use this starting point as a way to quickly set up a new project by generating files, installing gems, and more.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Funny Movies</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag  'application', 'data-turbolinks-track': 'reload' %>

  </head>

 <body class="bg-white">

  <% flash.each do |type, message| %>
    <% if type == "alert" %>
      <div class="bg-red-500">
        <div class="container px-2 mx-auto py-4 text-white text-center font-medium font-sans"><%= message %></div>
      </div>
    <% end %>
    <% if type == "notice" %>
      <div class="bg-green-500">
        <div class="container px-2 mx-auto py-4 text-white text-center font-medium font-sans"><%= message %></div>
      </div>
    <% end %>
  <% end %>

    <header class="mb-4">
      <nav class="flex items-center justify-between flex-wrap bg-gray-100 py-3 lg:px-10 px-3 text-gray-700 border-b border-gray-400">
        <div class="flex items-center flex-no-shrink mr-6">
          <%= image_tag 'home.png', style: 'height:10%;width:10%;' %>
          <%= link_to "Funny Movies", root_path, class:"link text-xl tracking-tight font-semibold" %>
        </div>
        <div class="block lg:hidden">
          <button class="flex items-center px-3 py-2 border rounded text-grey border-gray-500 hover:text-gray-600 hover:border-gray-600">
            <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
          </button>
        </div>
        <div class="w-full block lg:flex-1 lg:flex items-center text-center lg:text-left">

          <div class="w-full block lg:flex lg:flex-row lg:flex-1 mt-2 lg:mt-0 text-center lg:text-left lg:justify-end items-center">
            <% if user_signed_in? %>
             <%= link_to current_user.email  %>&nbsp;
            <%= link_to 'Share video', new_video_path, class:"btn btn-default" %>&nbsp;
             <%= link_to "Log out", destroy_user_session_path, method: :delete, class:"btn btn-default mb-2 lg:mr-2 lg:mb-0 block" %>
            <% else %>
               <%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
                 <%= f.label :email %>
                 <%= f.text_field :email %>
                 <%= f.label :password %>
                 <%= f.password_field :password %>
                <%= f.submit "Login/Register", class:"btn btn-default" %>
               <% end -%>
            <% end %>
          </div>
        </div>
      </nav>
    </header>

    <main class="lg:px-10 px-4">
      <%= content_for?(:content) ? yield(:content) : yield %>
    </main>
  </body>
</html>

app/views/videos/index.html.erb
<div class="container">
  <div class="row">
    <% @videos.each do |video| %>
      <div class="col-md-3 thumb video-thumb" data-video-id="<%= video.id %>">
        <table>
          <tr>
            <td>
              <iframe height="150" id="my-video" width="240" src="<%= video.video_url %>"
                frameborder="1" >
              </iframe>
            </td>
            <td>
              <table>
              <tr><td>
              Title: <%= video.name %>
              </td></tr>
              <tr><td>
                Shared by: <%= video.user.email %>
                <% if user_signed_in? %>
                <%= image_tag 'like.jpg', style: 'display:inline;height:5%;width:5%;'-%>
                <% end -%>
              </td></tr>
              <tr><td>
                <%=video.likes-%>
                <%= image_tag 'like.jpg', style: 'display:inline;height:2%;width:2%;'-%>
                <%=video.dislikes-%>
                <%= image_tag 'dislike.jpg', style: 'display:inline;height:2%;width:2%;'-%>
              <td></tr>
              <tr><td>
                  Description:
              </td></tr>
              <tr><td>
                    xxxx
              </td></tr>
              </table>
            </td>
          </tr>
          </table>
          <%= link_to 'Play', video,  class:"btn btn-default" %>
      </div>
    <% end %>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="pull-right">
      </div>
    </div>
  </div>
</div>

app/views/videos/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-sm-12">
      <h2>Share a Youtube video</h2>
      <%= simple_form_for @video, html: { multipart: true } do |f| %>
         <%= f.input :name %>
         <%= f.input :video_url %>
        <%= f.button :submit, class: 'btn-primary', value: 'Share Video' %>
      <% end %>
    </div>
  </div>
</div>

app/views/videos/show.html.erb
<div class="container">
  <div class="row video-full" data-video-id="<%= @video.id %>">
    <div class="col-md-10">
      <p class="small">
        <%= link_to 'Back to videos' ,videos_path %>
      </p>
      <h1>
        Title: <%= @video.name %>
      </h1>
        <iframe height="264" id="my-video" width="640" src="<%= @video.video_url %>"
          frameborder="1" >
        </iframe>
    </div>
    <div class="col-md-2">
      <h1>
        <span class="likes-count">
          Likes <%= @video.likes %>
        </span>
        <span class="glyphicon glyphicon-heart"></span>
      </h1>
    </div>
  </div>
</div>